_commit: v1.8.2
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: descheduler
helmRelease: descheduler
helmRepo: https://kubernetes-sigs.github.io/descheduler/
helmValues: helm/values.yaml
helmVersion: ''
homepageEnabled: false
ingress: false
labels: |-
  app.kubernetes.io/instance: descheduler
  app.kubernetes.io/name: descheduler
name: descheduler
namespace: descheduler
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://github.com/kubernetes-sigs/descheduler
url: https://github.com/charlesthomas/homelab-descheduler
